config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :home, only: [:index]
  resources :car_types, only: [:index]
  resources :car_colors, only: [:index]
  resources :bid_types, only: [:index]
  resources :car_models, only: [:index]
  resources :auctions
  resources :user_bids
  resources :user_reviews
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auction.rb
class Auction < ApplicationRecord

  belongs_to :car_color
  belongs_to :car_type
  belongs_to :car_model
  belongs_to :bid_type

  has_one_attached :image
end

app/models/bid_type.rb
class BidType < ApplicationRecord
end

app/models/car_color.rb
class CarColor < ApplicationRecord
  belongs_to :car_type
  validates_presence_of :color_name

  def name
    color_name
  end
end

app/models/car_model.rb
class CarModel < ApplicationRecord
end

app/models/car_type.rb
class CarType < ApplicationRecord
  has_many :car_colors, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_bid.rb
class UserBid < ApplicationRecord

  belongs_to :user
  belongs_to :auction
end

app/models/user_bid_review.rb
class UserBidReview < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  def index
    auctions = Auction.all
    @auctions = if params[:search].present?
                  filter_auctions = auctions
                  filter_auctions = auctions.where(car_type_id: params[:search][:car_type_id]) if params[:search][:car_type_id].present?
                  filter_auctions = auctions.where(car_color_id: params[:search][:car_color_id]) if params[:search][:car_color_id].present?
                  filter_auctions = auctions.where(car_model_id: params[:search][:car_model_id]) if params[:search][:car_model_id].present?
                  filter_auctions = auctions.where(bid_type_id: params[:search][:bid_type_id]) if params[:search][:bid_type_id].present?

                  filter_auctions
                else
                  auctions
                end
  end
end

app/controllers/bid_types_controller.rb
class BidTypesController < ApplicationController

  def index
    @bid_types = BidType.all
  end
end

app/controllers/car_types_controller.rb
class CarTypesController < ApplicationController

  def index
    @car_types = CarType.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bid_types_helper.rb
module BidTypesHelper
end

app/helpers/car_colors_helper.rb
module CarColorsHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_types_helper.rb
module CarTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_bids_helper.rb
module UserBidsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/views/auctions/_filter.html.erb
<%= simple_form_for :search, url: auctions_path, method: :get do |f| %>
  <div class="row mt-3">

    <div class="col-md-3">
      <label>Car type</label>
      <%= f.input :car_type_id, as: :select, collection: CarType.all, input_html: { class: "form-control" }, include_blank: "Select car type", label: false %>
    </div>

    <div class="col-md-3">
      <label>Car color</label>
      <%= f.input :car_color_id, as: :select, collection: CarColor.all, input_html: { class: "form-control" }, include_blank: "Select car color", label: false  %>
    </div>

    <div class="col-md-3">
      <label>Car model</label>
      <%= f.input :car_model_id, as: :select, collection: CarModel.all, input_html: { class: "form-control" }, include_blank: "Select car model", label: false  %>
    </div>

    <div class="col-md-3">
      <label>Bid type</label>
      <%= f.input :bid_type_id, as: :select, collection: BidType.all, input_html: { class: "form-control" }, include_blank: "Select bid type", label: false  %>
    </div>


  </div>

  <div class="mt-2">
    <%= f.submit "Search", class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/auctions/_index.html.erb
<% if @auctions.size == 0 %>
  <h3 class="mt-3 text-center">No auctions found!</h3>
<% else %>
  <div class="row mt-3">
    <% @auctions.each do |auction| %>
      <div class="col-md-6">
        <div class="card">
          <% if auction.image.attached? %>
            <%= image_tag auction.image, class: "card-img-top", style: "width: 100%; height: 250px;" %>
          <% end %>
          <div class="card-body">
            <p class="card-text">
            <div class="row mt-2">
              <div class="col-md-3"><strong>Date</strong></div>
              <div class="col-md-8"><%= auction.date %></div>
            </div>


            <div class="row mt-2">
              <div class="col-md-3"><strong>Car type</strong></div>
              <div class="col-md-8"><%= auction.car_type.name %></div>
            </div>

            <div class="row mt-2">
              <div class="col-md-3"><strong>Car color</strong></div>
              <div class="col-md-8"><%= auction.car_color.color_name %></div>
            </div>

            <div class="row mt-2">
              <div class="col-md-3"><strong>Car model</strong></div>
              <div class="col-md-8"><%= auction.car_model.name %></div>
            </div>

            <div class="row mt-2">
              <div class="col-md-3"><strong>Bid type</strong></div>
              <div class="col-md-8"><%= auction.bid_type.name %></div>
            </div>

            <div class="row mt-2">
              <div class="col-md-3"><strong>Minimum amount</strong></div>
              <div class="col-md-8"><%= auction.minimum_amount %></div>
            </div>

            <div class="row mt-2">
              <div class="col-md-3"><strong>Maximum amount</strong></div>
              <div class="col-md-8"><%= auction.maximum_amount %></div>
            </div>

            <div class="mt-2">
              <% unless UserBid.find_by(user: current_user, auction: auction).nil? %>
                <% if UserBidReview.find_by(user: current_user, auction: auction).nil? %>
                  <a href="/user_reviews/new?auction_id=<%= auction.id %>" class="btn btn-sm btn-outline-primary float-end">Place
                    your review</a>
                <% end %>
              <% end %>
              <% if UserBid.find_by(user: current_user, auction: auction).nil? %>
                <a href="/user_bids/new?auction_id=<%= auction.id %>" class="btn btn-sm btn-outline-primary float-end">Place
                  your bid</a>
              <% end %>
              <a href="/user_bids?auction_id=<%= auction.id %>" class="btn btn-sm btn-outline-primary ml-3">Bids</a>
              <a href="/user_reviews?auction_id=<%= auction.id %>" class="btn btn-sm btn-outline-primary ml-3">Reviews</a>
            </div>

            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/auctions/index.html.erb
<%= render "auctions/filter" %>

<div class="auctions-list">
  <%= render "auctions/index" %>
</div>

app/views/auctions/index.js.erb
$("#auctions-list").html("<%= escape_javascript(render("auctions/index")) %>");